using Albatross.CommandLine;
using Albatross.CommandLine.Outputs;
using Albatross.CommandLine.Defaults;
using Microsoft.Extensions.DependencyInjection;
using System.CommandLine;
using CustomRootCommandConsole.AutoGenerated;
using Albatross.CommandLine.Annotations;

namespace CustomRootCommandConsole {
	static class Program {
		static async Task<int> Main(string[] args) {
			await using var host = new CommandHost("A Test Console Program");
			host.RegisterServices((result, services) => RegisterServices(result, services))
				.Parse(args, false)
				.WithDefaults(AppContext.BaseDirectory)
				.Build();
			return await host.InvokeAsync();
		}
		static void RegisterServices(ParseResult result, IServiceCollection services) {
			services.AddSingleton<ICommandErrorHandler, GlobalErrorHandler>();
			services.RegisterCommands();
		}
	}

	// [Verb<TestRoot>("")]
	public class TestRootParams {
	}

	public class TestRoot : BaseHandler<TestRootParams> {
		public TestRoot(ParseResult result, TestRootParams parameters) : base(result, parameters) {
		}

		public override Task<int> InvokeAsync(CancellationToken cancellationToken) {
			System.Console.WriteLine("test");
			return Task.FromResult(0);
		}
	}
}