using Albatross.CommandLine;
using Albatross.Config;
using Albatross.Logging;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using System.CommandLine;
using System.IO;

namespace Sample.CommandLine {
	public class MySetup : Setup {
		public MySetup() : base("This a sample commandline program") {
		}

		protected override void RegisterServices(ParseResult result, IConfiguration configuration, EnvironmentSetting envSetting, IServiceCollection services) {
			base.RegisterServices(result, configuration, envSetting, services);
			services.AddShortenLoggerName(false, "Albatross", "Sample");
			// RegisterCommands method is generated by codegen
			services.RegisterCommands();
			// register your dependencies here
			services.AddSingleton<IMyService, MyService>();

			services.AddScoped<ColorCommandOptions>(provider => { 
				var result = provider.GetRequiredService<ParseResult>();
				return new ColorCommandOptions {
					Name = result.GetRequiredValue<string>("--name"),
					Data = result.GetRequiredValue<int>("--data"),
					MyFile = result.GetRequiredValue<FileInfo>("--myfile")!,
					SecondFile = result.GetRequiredValue<FileInfo>("--second")!,
				};
			});
		}
	}
}