using Albatross.CommandLine;
using Albatross.Config;
using Albatross.Logging;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using System.CommandLine;
using System.IO;
using System.Xml.XPath;

namespace Sample.CommandLine {
	public class MySetup : Setup {
		public MySetup() : base("This a sample commandline program") {
		}

		protected override void RegisterServices(ParseResult result, IConfiguration configuration, EnvironmentSetting envSetting, IServiceCollection services) {
			base.RegisterServices(result, configuration, envSetting, services);
			services.AddShortenLoggerName(false, "Albatross", "Sample");
			// RegisterCommands method is generated by codegen
			services.RegisterCommands();
			// register your dependencies here
			services.AddSingleton<IMyService, MyService>();
			// conditional registration based on command
			var key = result.CommandResult.Command.GetCommandKey();
			if (key.StartsWith("csharp ")) {
				// register csharp command specific services
				services.AddSingleton<ICodeGenerator, CSharpCodeGenerator>();
			}else if (key.StartsWith("typescript ")) {
				// register typescript command specific services
				services.AddSingleton<ICodeGenerator, TypeScriptCodeGenerator>();
			}
		}
	}
}