using System.Threading.Tasks;
using Albatross.CommandLine;
using Albatross.CommandLine.Defaults;
using Albatross.Config;
using Microsoft.Extensions.DependencyInjection;
using System.CommandLine;
using Sample.CommandLine.Services;

namespace Sample.CommandLine {
	internal class Program {
		static async Task<int> Main(string[] args) {
			Albatross.Logging.Extensions.RemoveLegacySlackSinkOptions();
			await using var host = new CommandHost("Sample Command Line Application");
			// do this if you want to change the global verbosity default
			// CommandBuilder.VerbosityOption.DefaultValueFactory = _ => "Info";
			host.RegisterServices(RegisterServices)
				// this method is generated by source generator
				.AddCommands()
				// this is a custom command added manually
				.AddCommand("test", new ManualCommand())
				.Parse(args, false)
				.WithDefaults()
				.Build();
			return await host.InvokeAsync();
		}
		
		static void RegisterServices(ParseResult result, IServiceCollection services) {
			services.AddConfig<SampleConfig>();
			// This method is generated by codegen
			services.RegisterCommands();

			services.AddSingleton<IMyService, MyService>();

			// conditional registration based on command
			var key = result.CommandResult.Command.GetCommandKey();
			if (key.StartsWith("csharp ")) {
				// register csharp command specific services
				services.AddSingleton<ICodeGenerator, CSharpCodeGenerator>();
			} else if (key.StartsWith("typescript ")) {
				// register typescript command specific services
				services.AddSingleton<ICodeGenerator, TypeScriptCodeGenerator>();
			}
			services.AddScoped<InstrumentService>();
		}
	}
}