using Albatross.CommandLine;
using Albatross.CommandLine.Outputs;
using Albatross.CommandLine.Defaults;
using Albatross.Config;
using Microsoft.Extensions.DependencyInjection;
using System.CommandLine;
using TopLevelStatementConsole.AutoGenerated;

var appPath = new ApplicationPath(false, ["top-level-test"], "top-level-test", null, args);
appPath.Init();
await using var host = new CommandHost("A Test Console Program");
host.RegisterServices((result, services) => RegisterServices(result, services, appPath))
	// this method is generated by source generator
	.AddCommands()
	.Parse(args, false)
	.WithDefaults(appPath.ConfigRoot)
	.Build();
return await host.InvokeAsync();


static void RegisterServices(ParseResult result, IServiceCollection services, IApplicationPath appPath) {
	services.AddSingleton(appPath);
	services.AddSingleton<ICommandErrorHandler, GlobalErrorHandler>();
	services.RegisterCommands();
}