using Albatross.CommandLine.Annotations;
using Albatross.CommandLine.Test.AutoGenerated;
using Albatross.CommandLine.Test.CodeGen;
using Microsoft.Extensions.DependencyInjection;
using System.CommandLine;
using Xunit;

// Assembly-level verb: the command is declared here rather than by annotating the params class,
// exercising the generator's [Verb<TParams, THandler>] code path.
[assembly: Verb<AssemblyLevelParams, AssemblyLevelHandler>("assembly-level", Description = "A test verb declared at the assembly level")]

namespace Albatross.CommandLine.Test.CodeGen {
	// Intentionally NOT annotated with [Verb] - the assembly-level attribute above drives generation.
	public record AssemblyLevelParams {
		[Option("n")]
		public required string Name { get; init; }
	}

	public class AssemblyLevelHandler : IAsyncCommandHandler {
		public Task<int> InvokeAsync(CancellationToken cancellationToken) => Task.FromResult(0);
	}

	/// <summary>
	/// Verifies the generator produces a command class, DI registration, and handler wiring for a verb
	/// declared with the assembly-level <c>[Verb&lt;TParams, THandler&gt;]</c> attribute (no annotated params class).
	/// </summary>
	public class AssemblyLevelVerb {
		[Fact]
		public void CommandClassIsGenerated() {
			var host = new CommandHost("test");
			host.AddCommands();
			host.CommandBuilder.BuildTree(host.GetServiceProvider);
			Assert.True(host.CommandBuilder.TryGetCommand("assembly-level", out Command cmd));
			Assert.IsType<AssemblyLevelCommand>(cmd);
		}

		[Fact]
		public void ParamsAndHandlerAreRegistered() {
			// Add only this command (see note in Binding.Resolve about duplicate names in other fixtures).
			var host = new CommandHost("test");
			host.CommandBuilder.Add<AssemblyLevelCommand>("assembly-level");
			host.RegisterServices((_, services) => services.RegisterCommands());
			host.Parse(["assembly-level", "--name", "abc"]);
			host.Build();
			var provider = host.GetServiceProvider();
			var @params = provider.GetService<AssemblyLevelParams>();
			Assert.NotNull(@params);
			Assert.Equal("abc", @params.Name);
			var handler = provider.GetRequiredKeyedService<IAsyncCommandHandler>("assembly-level");
			Assert.IsType<AssemblyLevelHandler>(handler);
		}
	}
}
