using Albatross.CommandLine.Annotations;
using Albatross.CommandLine.Test.AutoGenerated;
using Microsoft.Extensions.DependencyInjection;
using Xunit;

namespace Albatross.CommandLine.Test.CodeGen {
	[Verb<BindingHandler>("test binding", Description = "A test verb for parse-and-bind behavior")]
	public record BindingParams {
		[Argument(Description = "A required positional argument")]
		public required string TextArgument { get; init; }

		[Option("n")]
		public required string Name { get; init; }

		[Option]
		public int? Count { get; init; }

		[Option]
		public int[] Numbers { get; init; } = Array.Empty<int>();

		[Option]
		public bool Flag { get; init; }
	}

	public class BindingHandler : IAsyncCommandHandler {
		public Task<int> InvokeAsync(CancellationToken cancellationToken) => Task.FromResult(0);
	}

	/// <summary>
	/// Behavioral tests: parse real arguments and assert the values that the generated
	/// <c>RegisterCommands()</c> factory binds onto the params class.  Unlike the structural tests, these
	/// exercise the generated <c>GetValue&lt;T&gt;()</c> / <c>GetRequiredValue&lt;T&gt;()</c> binding
	/// expressions - including the <c>?? Array.Empty&lt;T&gt;()</c> fallback and nullable handling.
	/// </summary>
	public class Binding {
		static BindingParams Resolve(params string[] args) {
			// Add only the command under test rather than AddCommands(): other fixtures (e.g. the
			// alias-dedup "test explicit-option") intentionally contain duplicate option names, which
			// System.CommandLine rejects when a value is looked up by name across the shared tree.
			var host = new CommandHost("test");
			host.CommandBuilder.Add<BindingCommand>("test binding");
			host.RegisterServices((_, services) => services.RegisterCommands());
			host.Parse(args);
			host.Build();
			return host.GetServiceProvider().GetRequiredService<BindingParams>();
		}

		[Fact]
		public void BindsAllSuppliedValues() {
			var p = Resolve("test", "binding", "hello", "--name", "world", "--count", "5", "--numbers", "1", "--numbers", "2", "--flag");
			Assert.Equal("hello", p.TextArgument);
			Assert.Equal("world", p.Name);
			Assert.Equal(5, p.Count);
			Assert.Equal(new[] { 1, 2 }, p.Numbers);
			Assert.True(p.Flag);
		}

		[Fact]
		public void OmittedOptionalValueBindsToNull() {
			var p = Resolve("test", "binding", "hello", "--name", "world");
			Assert.Null(p.Count);
		}

		[Fact]
		public void OmittedArrayBindsToEmptyNotNull() {
			// exercises the generated "GetValue<int[]>(...) ?? Array.Empty<int>()" fallback
			var p = Resolve("test", "binding", "hello", "--name", "world");
			Assert.NotNull(p.Numbers);
			Assert.Empty(p.Numbers);
		}

		[Fact]
		public void OmittedBooleanBindsToFalse() {
			var p = Resolve("test", "binding", "hello", "--name", "world");
			Assert.False(p.Flag);
		}
	}
}
