using Albatross.CommandLine.Annotations;
using Albatross.CommandLine.Test.AutoGenerated;
using Xunit;

namespace Albatross.CommandLine.Test.CodeGen {
	[Verb("collide one", Description = "command-class-name collision test A")]
	public record CollideParams { }

	// No "Params" suffix: GetCommandClassName maps BOTH this and CollideParams to "CollideCommand",
	// so the generator must disambiguate the second one by appending an index (RenameCommandClass).
	[Verb("collide two", Description = "command-class-name collision test B")]
	public record Collide { }

	/// <summary>
	/// Two params classes whose derived command-class names collide (both "CollideCommand") must be generated
	/// as distinct types, with one suffixed by an index rather than clashing.
	/// </summary>
	public class CommandClassNameCollision {
		[Fact]
		public void CollidingCommandClassesAreDisambiguated() {
			var host = new CommandHost("test");
			host.AddCommands();
			host.CommandBuilder.BuildTree(host.GetServiceProvider);
			Assert.True(host.CommandBuilder.TryGetCommand("collide one", out var one));
			Assert.True(host.CommandBuilder.TryGetCommand("collide two", out var two));
			Assert.NotEqual(one.GetType(), two.GetType());
			var typeNames = new[] { one.GetType().Name, two.GetType().Name };
			Assert.Contains("CollideCommand", typeNames);
			Assert.Contains("CollideCommand1", typeNames);
		}
	}
}
