using Albatross.CommandLine.Annotations;
using Albatross.CommandLine.Test.AutoGenerated;
using System.CommandLine;
using System.Linq;
using Xunit;

namespace Albatross.CommandLine.Test.CodeGen {
	[Verb("hier alpha", Description = "hierarchy test leaf A")]
	public record HierAlphaParams { }

	[Verb("hier beta", Description = "hierarchy test leaf B")]
	public record HierBetaParams { }

	[Verb("hier sub leaf", Description = "hierarchy test deep leaf")]
	public record HierSubLeafParams { }

	/// <summary>
	/// Verifies AddCommands() builds the parent/child hierarchy from space-separated verb names: intermediate
	/// parents are auto-created, sibling commands share one parent instance, and nesting works three levels deep.
	/// </summary>
	public class CommandHierarchy {
		static CommandBuilder BuildTree() {
			var host = new CommandHost("test");
			host.AddCommands();
			host.CommandBuilder.BuildTree(host.GetServiceProvider);
			return host.CommandBuilder;
		}

		static Command Parent(Command command) => command.Parents.OfType<Command>().Single();

		[Fact]
		public void IntermediateParentIsAutoCreated() {
			var builder = BuildTree();
			Assert.True(builder.TryGetCommand("hier", out var hier));
			Assert.NotNull(hier);
		}

		[Fact]
		public void SiblingsShareTheSameParentInstance() {
			var builder = BuildTree();
			Assert.True(builder.TryGetCommand("hier", out var hier));
			Assert.True(builder.TryGetCommand("hier alpha", out var alpha));
			Assert.True(builder.TryGetCommand("hier beta", out var beta));
			Assert.Same(hier, Parent(alpha));
			Assert.Same(hier, Parent(beta));
		}

		[Fact]
		public void NestingWorksThreeLevelsDeep() {
			var builder = BuildTree();
			Assert.True(builder.TryGetCommand("hier", out var hier));
			Assert.True(builder.TryGetCommand("hier sub", out var sub));
			Assert.True(builder.TryGetCommand("hier sub leaf", out var leaf));
			Assert.Same(hier, Parent(sub));
			Assert.Same(sub, Parent(leaf));
		}
	}
}
