using Albatross.CommandLine.Annotations;
using Albatross.CommandLine.Test.AutoGenerated;
using Microsoft.Extensions.DependencyInjection;
using System.IO;
using Xunit;

namespace Albatross.CommandLine.Test.CodeGen {
	public enum TrafficLight { Red, Green, Blue }

	[Verb<TypeConversionHandler>("test type-conversion", Description = "A test verb covering non-primitive option types")]
	public record TypeConversionParams {
		[Option]
		public TrafficLight Light { get; init; }

		[Option]
		public FileInfo? File { get; init; }
	}

	public class TypeConversionHandler : IAsyncCommandHandler {
		public Task<int> InvokeAsync(CancellationToken cancellationToken) => Task.FromResult(0);
	}

	/// <summary>
	/// Behavioral tests for option types beyond string/int/bool: an enum (bound via GetRequiredValue&lt;TEnum&gt;)
	/// and a FileInfo.  Adds only this command to the tree to avoid the duplicate-name fixtures elsewhere
	/// (see the note in Binding.Resolve).
	/// </summary>
	public class TypeConversions {
		static TypeConversionParams Resolve(params string[] args) {
			var host = new CommandHost("test");
			host.CommandBuilder.Add<TypeConversionCommand>("test type-conversion");
			host.RegisterServices((_, services) => services.RegisterCommands());
			host.Parse(args);
			host.Build();
			return host.GetServiceProvider().GetRequiredService<TypeConversionParams>();
		}

		[Fact]
		public void BindsEnumOptionByName() {
			var p = Resolve("test", "type-conversion", "--light", "Green");
			Assert.Equal(TrafficLight.Green, p.Light);
		}

		[Fact]
		public void BindsFileInfoOption() {
			var p = Resolve("test", "type-conversion", "--light", "Red", "--file", "data.txt");
			Assert.NotNull(p.File);
			Assert.Equal("data.txt", p.File!.Name);
		}

		[Fact]
		public void OmittedFileInfoBindsToNull() {
			var p = Resolve("test", "type-conversion", "--light", "Red");
			Assert.Null(p.File);
		}
	}
}
